In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv('./data.csv').iloc[:, 1:]
data.head(10)

,error,mean_dt,name,dt,e_terms,adaptive,scheme,rho
0,-1.131684,0.010000,"Euler, dt=0.01",0.01,0,False,euler,NaN
1,0.237676,0.010000,"Euler, dt=0.01",0.01,0,False,euler,NaN
2,-1.131684,0.010000,"Milstein, dt=0.01",0.01,0,False,milstein,NaN
3,0.237676,0.010000,"Milstein, dt=0.01",0.01,0,False,milstein,NaN
4,-1.131684,0.090909,"Euler ad, dt=0.01, eterms=1, rho=0.1",0.01,1,True,euler,0.1
5,0.237676,0.090909,"Euler ad, dt=0.01, eterms=1, rho=0.1",0.01,1,True,euler,0.1
6,-1.131684,0.090909,"Euler ad, dt=0.01, eterms=2, rho=0.1",0.01,2,True,euler,0.1
7,0.237676,0.090909,"Euler ad, dt=0.01, eterms=2, rho=0.1",0.01,2,True,euler,0.1
8,-1.131684,0.090909,"Milstein ad, dt=0.01, eterms=1, rho=0.1",0.01,1,True,milstein,0.1
9,0.237676,0.090909,"Milstein ad, dt=0.01, eterms=1, rho=0.1",0.01,1,True,milstein,0.1

In [12]:
gb = data.groupby('scheme adaptive e_terms rho'.split(), dropna=False)#, 'e_terms', 'rho'])
for _, df in gb:
  name = df.name[0]
  z = df.groupby('dt').error

       error  mean_dt             name     dt  e_terms  adaptive scheme  rho
0  -1.131684    0.010   Euler, dt=0.01  0.010        0     False  euler  NaN
1   0.237676    0.010   Euler, dt=0.01  0.010        0     False  euler  NaN
16 -1.131684    0.001  Euler, dt=0.001  0.001        0     False  euler  NaN
17  0.237676    0.001  Euler, dt=0.001  0.001        0     False  euler  NaN